script: 'ci/travis.rb'
before_install:
  - gem install bundler
rvm:
  - 1.9.3
  - 2.0.0
env:
  - "GEM=railties"
  - "GEM=ap,am,amo,ares,as"
  - "GEM=ar:mysql"
  - "GEM=ar:mysql2"
  - "GEM=ar:sqlite3"
  - "GEM=ar:postgresql"
matrix:
  allow_failures:
    - rvm: 2.0.0
notifications:
  email:
    - l8ww0frr3rzvj0rs0u9q@sikachu.com
bundler_args: --path vendor/bundle
branches:
  only:
    - 3-2-stable-ruby-2
